version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_DB: "simple_psp"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - /data/postgress:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pedrohlcastro@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "8080:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge